language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
    - sudo apt-get update > /dev/null

matrix:
    allow_failures:
        php: hhvm

script:
    - composer self-update
    - composer update -n
    - ./bin/phpspec run -f pretty
    - ./bin/behat --no-snippets --no-paths --verbose --format=progress

notifications:
  irc: "irc.freenode.org#fsi-open"
